- name: Cleanup unused Docker images
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Prune unused Docker images
      shell: docker image prune -a
      args:
        warn: false
