- name: List all running Docker containers
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Get running Docker container names
      shell: docker ps --format '{{.Names}}'
      register: running_containers
      changed_when: false

    - name: Print running container names
      debug:
        msg: "{{ item.Name }}"
      loop: "{{ running_containers }}"
