- name: List all running Docker containers
  hosts: all
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: Get running Docker container names
      shell: >
        {% raw %}
        docker ps --format '{{.Names}}'
        {% endraw %}
      register: running_containers
    - debug:
        msg: "{{ running_containers.stdout_lines }}"
