- name: apt upgrade
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Upgrade installed packages safely
      ansible.builtin.apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes
