- name: apt dist upgrade
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Upgrade installed packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes
